create table if not exists public.minecraft_application_emails (
    id bigint generated by default as identity primary key,
    email_hash text not null unique,
    submitted_at timestamptz not null default now()
);
